<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<test-results name="E:\0Tony_GitHub\DUnitX_ex1\Win32\Debug\MyTestConsole.exe" total="4" errors="0" failures="1" ignored="0" inconclusive="0" not-run="0" skipped="0" invalid="0" date="2020-12-30" time="0.041">
  <culture-info current-culture="en" current-uiculture="en" />
  <test-suite type="Assembly" name="MyTestConsole.exe" executed="true" result="Failure" success="False" time="0.041" asserts="0">
    <results>
        <test-suite type="Namespace" name="UnitMyTest" executed="true" result="Failure" success="False" time="0.041" asserts="0" >
          <results>
              <test-suite type="Fixture" name="TMyTestObject" executed="True" result="Failure" success="False" time="0.041" >
                <results>
                  <test-case name="Test_MyAdd.TestA" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Test_MyAdd.TestB" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Test_MySub.TestA" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Test_MySub.TestB" executed="True" result="Failure" success="False" time="0.000" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Expected -1 is not equal to actual 0  ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
          </results>
        </test-suite>
    </results>
  </test-suite>
</test-results>
